apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q2ccua176-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q2ccua176-go 
  name: q2ccua176-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q2ccua176-go 
